Update workflow
Signed-off-by: Udit Gaurav <udit.gaurav@harness.io>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -2,36 +2,38 @@ name: Release
 on:
   push:
     tags:
-    - 'v[0-9]+.[0-9]+.[0-9]+'
-    
+      - 'v[0-9]+.[0-9]+.[0-9]+'
+
 env:
   BIN_NAME: chaos-lambda-extension
   PROJECT_NAME: chaos-lambda-extension
+
 jobs:
   build-artifacts:
     name: Build artifacts
     runs-on: ${{ matrix.os }}
     strategy:
-      fail-fast: false # don't fail other jobs if one fails
+      fail-fast: false  # don't fail other jobs if one fails
       matrix:
         build: [x86_64-linux, aarch64-linux] 
         include:
-        - build: x86_64-linux
-          os: ubuntu-20.04
-          rust: stable
-          target: x86_64-unknown-linux-gnu
-          cross: false
-        - build: aarch64-linux
-          os: ubuntu-20.04
-          rust: stable
-          target: aarch64-unknown-linux-gnu
-          cross: true
+          - build: x86_64-linux
+            os: ubuntu-20.04
+            rust: stable
+            target: x86_64-unknown-linux-gnu
+            cross: false
+          - build: aarch64-linux
+            os: ubuntu-20.04
+            rust: stable
+            target: aarch64-unknown-linux-gnu
+            cross: true
     outputs:
       target: ${{ matrix.target }}
 
     steps:
       - name: Checkout sources
         uses: actions/checkout@v2
+
       - uses: Swatinem/rust-cache@v2
       - name: Install ${{ matrix.rust }} toolchain
         uses: actions-rs/toolchain@v1
@@ -40,14 +42,17 @@ jobs:
           toolchain: ${{ matrix.rust }}
           target: ${{ matrix.target }}
           override: true
-      - name: install cargo lambda
+
+      - name: Install cargo lambda
         run: pip3 install cargo-lambda
+
       - name: Run cargo test
         uses: actions-rs/cargo@v1
         with:
           use-cross: ${{ matrix.cross }}
           command: test
           args: --release --locked --target ${{ matrix.target }} -- --test-threads=1
+
       - uses: taiki-e/install-action@just
       - name: Build release binary 
         run: just build-extension release ${{ matrix.target }}
@@ -70,6 +75,7 @@ jobs:
         run: |
           mkdir dist
           cp "./target/lambda/extensions/$BIN_NAME" "dist/"
+
       - uses: actions/upload-artifact@v2.2.4
         with:
           name: bins-${{ matrix.target }}
@@ -84,12 +90,7 @@ jobs:
     strategy:
       matrix:
         target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
-        region: [
-          us-east-1, us-east-2, us-west-1, us-west-2, eu-central-1,
-          eu-west-1, eu-west-2, eu-west-3, eu-north-1, ca-central-1,
-          ap-south-1, ap-northeast-3, ap-northeast-2, ap-northeast-1,
-          ap-southeast-1, ap-southeast-2, sa-east-1
-        ]
+        region: [us-west-2]  # Only push to us-west-2
     steps:
       - name: Checkout sources
         uses: actions/checkout@v2
@@ -97,17 +98,21 @@ jobs:
         with:
           name: bins-${{ matrix.target }}
           path: target/lambda/extensions
+
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-region: ${{ matrix.region }}
-          role-to-assume: arn:aws:iam::871265522301:role/GitHub-Deploy-Layers-Role
+          aws-region: ${{ secrets.AWS_REGION }}  # Use secret for AWS region
+          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # Use secret for role ARN
           role-session-name: GitHubActionsSession
-      - uses: taiki-e/install-action@just
-      - name: Upload layer to ${{ matrix.region }}
-        run: set -e; just deploy-extension release ${{ matrix.region }} ${{ matrix.target }} | tee >(jq -r '.LayerArn, .Version' | (read layer; read version; just apply-global-permission-to-layer "$layer" "$version"))
-      
 
+      - uses: taiki-e/install-action@just
+
+      - name: Upload layer to ${{ matrix.region }}
+        run: |
+          set -e
+          just deploy-extension release ${{ matrix.region }} ${{ matrix.target }} | tee >(jq -r '.LayerArn, .Version' | (read layer; read version; just apply-global-permission-to-layer "$layer" "$version"))
+  
   update-layer-readme:
     name: Update LAYERS.md
     runs-on: ubuntu-20.04
@@ -120,18 +125,32 @@ jobs:
         uses: actions/checkout@v2
         with:
           ref: main
-          fetch-depth: 0 # To get all tags
+          fetch-depth: 0  # To get all tags
           token: ${{ secrets.UPDATE_LAYERS_SECRET }}
+
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v2
         with:
-          aws-region: us-east-1
-          role-to-assume: arn:aws:iam::871265522301:role/GitHub-Deploy-Layers-Role
+          aws-region: ${{ secrets.AWS_REGION }}  # Use secret for AWS region
+          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}  # Use secret for role ARN
           role-session-name: GitHubActionsSession
+
       - name: Update LAYERS.md with arm
-        run: set -e; echo "# ARM64" > LAYERS.md && for region in $(aws ec2 describe-regions --query "Regions[].RegionName" --output text); do aws lambda list-layer-versions --layer-name chaos-lambda-extension-aarch64-unknown-linux-gnu-release --region $region --query 'LayerVersions[0].LayerVersionArn' --output text | tee -a LAYERS.md; echo "" >> LAYERS.md; done
+        run: |
+          set -e; echo "# ARM64" > LAYERS.md
+          for region in $(aws ec2 describe-regions --query "Regions[].RegionName" --output text); do
+            aws lambda list-layer-versions --layer-name chaos-lambda-extension-aarch64-unknown-linux-gnu-release --region $region --query 'LayerVersions[0].LayerVersionArn' --output text | tee -a LAYERS.md
+            echo "" >> LAYERS.md
+          done
+
       - name: Update LAYERS.md with X86
-        run: set -e; echo "# X86-64" >> LAYERS.md; for region in $(aws ec2 describe-regions --query "Regions[].RegionName" --output text); do aws lambda list-layer-versions --layer-name chaos-lambda-extension-x86_64-unknown-linux-gnu-release --region $region --query 'LayerVersions[0].LayerVersionArn' --output text | tee -a LAYERS.md; echo "" | tee -a LAYERS.md; done
+        run: |
+          set -e; echo "# X86-64" >> LAYERS.md
+          for region in $(aws ec2 describe-regions --query "Regions[].RegionName" --output text); do
+            aws lambda list-layer-versions --layer-name chaos-lambda-extension-x86_64-unknown-linux-gnu-release --region $region --query 'LayerVersions[0].LayerVersionArn' --output text | tee -a LAYERS.md
+            echo "" | tee -a LAYERS.md
+          done
+
       - uses: stefanzweifel/git-auto-commit-action@v4
         with:
           commit_message: Update LAYERS.md
@@ -175,11 +194,9 @@ jobs:
               platform=${dir#"bins-"}
               pkgname=$PROJECT_NAME-$TAG-$platform
               mkdir tmp/$pkgname
-              # cp LICENSE README.md tmp/$pkgname
               mv bins-$platform/$BIN_NAME tmp/$pkgname
               chmod +x tmp/$pkgname/$BIN_NAME
               tar cJf dist/$pkgname.tar.xz -C tmp $pkgname
-              
           done
 
       - name: Upload binaries to release
@@ -195,4 +212,3 @@ jobs:
         id: extract-version
         run: |
           printf "::set-output name=%s::%s\n" tag-name "${GITHUB_REF#refs/tags/}"
-      
